version: '3.3'
# networks:
#     dockernet:
#       external:
#         name: dockernet
#networks:
#    internal:
#        driver: bridge
# Dependencies:

# vfb-kb
## vfb-kb2kb
### vfb-validatekb
#### vfb-collectdata

# vfb-triplestore
## vfb-updatetriplestore

# vfb-dumps
# vfb-owlery

# vfb-prod
## vfb-updateprod


services:
  vfb-kb:
    # image: virtualflybrain/docker-neo4j-knowledgebase:neo2owl
    # image: virtualflybrain/docker-vfb-neo4j:enterprise
    image: virtualflybrain/vfb-prod:kb
    build:
      context: ../docker-neo4j-knowledgebase
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: 6G
    #   restart_policy:
    #     condition: on-failure
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_memory_heap_maxSize=15G
      - NEO4J_dbms_memory_heap_initial__size=1G
      #- NEO4J_dbms_memory_pagecache_size=20G
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - vfb_data:/data_transfer
    deploy:
      resources:
        limits:
          memory: 25G
        reservations:
          memory: 1G
  vfb-triplestore:
    image: matentzn/vfb-pipeline-triplestore
    environment:
      - JVM_PARAMS=-Xms1G -Xmx5G
      - RDF4J_DATA=/data
    ports:
      - 8181:8080
  vfb-prod:
    image: virtualflybrain/vfb-prod:latest
    build:
      context: ../vfb-prod
      dockerfile: Dockerfile
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_memory_heap_maxSize=3G
      - NEO4J_dbms_memory_heap_initial__size=1G
    ports:
      - 7473:7474
      - 7686:7686
    volumes:
      - vfb_data:/input
    # networks:
    #   - dockernet
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://vfb-prod:7473" ]
      interval: 18s
      timeout: 12s
      retries: 3
  # vfb-kb2kb:
  #   image: matentzn/vfb-pipeline-kb2kb:latest
  #   depends_on:
  #     - vfb-kb
  #   links:
  #     - vfb-kb
  #   environment:
  #     - KBpassword=neo4j/neo
  #     - KBserver=http://vfb-kb:7474
#    networks:
#      - dockernet
  vfb-validatekb:
    image: matentzn/vfb-pipeline-validatekb:latest
    build:
      context: ../vfb-pipeline-validatekb
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-kb
    links:
      - vfb-kb
    environment:
      - KBpassword=neo4j/neo
      - KBserver=http://vfb-kb:7474
#    networks:
#      - dockernet
  vfb-collectdata:
    image: matentzn/vfb-pipeline-collectdata:latest
    build:
      context: ../vfb-pipeline-collectdata
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-kb
      - vfb-validatekb
    links:
      - vfb-kb
    environment:
      - KBserver=http://vfb-kb:7474
    volumes:
      - vfb_data:/out
#    networks:
#      - dockernet
  vfb-updatetriplestore:
    image: matentzn/vfb-pipeline-updatetriplestore:latest
    build:
      context: ../vfb-pipeline-updatetriplestore
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-collectdata
      - vfb-triplestore
    links:
      - vfb-triplestore
    environment:
      - SERVER=http://vfb-triplestore:8080
    volumes:
      - vfb_data:/data
#    networks:
#      - dockernet
  vfb-updateprod:
    image: matentzn/vfb-pipeline-update-prod:latest
    build:
      context: ../vfb-pipeline-update-prod
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-dumps
      - vfb-prod
    links:
      - vfb-dumps
      - vfb-prod
    environment:
      - password=neo4j/neo
      - server=http://vfb-prod:7474
    volumes:
      - vfb_data:/input
#    networks:
#      - dockernet
  vfb-owlery:
    image: phenoscape/owlery
    build:
      context: ../owlery-vfb
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-dumps
    links:
      - vfb-dumps
    ports:
      - 80:8080
#    networks:
#      - dockernet
  vfb-dumps:
    image: matentzn/vfb-pipeline-dumps:latest
    build:
      context: ../vfb-pipeline-dumps
      dockerfile: Dockerfile
      args:
        - CONF_REPO=${CONF_REPO}
        - CONF_BRANCH=${CONF_BRANCH}
    depends_on:
      - vfb-updatetriplestore
      - vfb-triplestore
    links:
      - vfb-triplestore
    volumes:
      - vfb_data:/out
#    networks:
#      - dockernet
  solr:
    image: virtualflybrain/vfb-solr
    ports:
     - 8993:8983
    depends_on:
      - vfb-dumps
    links:
      - vfb-dumps
    volumes:
      - solr_data:/var/solr
    entrypoint:
    - bash
    - "-c"
    - "precreate-core ontology; precreate-core bdsdump; exec solr -f"
  #    networks:
  #      - dockernet
volumes:
  vfb_data:
  solr_data:
